name: 'RepoSec Security Scan'
description: 'Scan repository for common security vulnerabilities across languages'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  severity:
    description: 'Minimum severity to report (critical, high, medium, low)'
    required: false
    default: 'medium'
  format:
    description: 'Output format (terminal, json, markdown)'
    required: false
    default: 'terminal'
  path:
    description: 'Path to scan'
    required: false
    default: '.'
  config:
    description: 'Path to .reposec.yml config file'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install RepoSec
      shell: bash
      run: pip install reposec

    - name: Run Security Scan
      shell: bash
      run: |
        ARGS=(scan "${{ inputs.path }}" --severity "${{ inputs.severity }}" --format "${{ inputs.format }}")
        if [ -n "${{ inputs.config }}" ]; then
          ARGS+=(--config "${{ inputs.config }}")
        fi
        reposec "${ARGS[@]}"
